import { cp, readdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
await cp('public','dist',{recursive:true});
async function files(dir, prefix='') {
  const out=[];
  for (const entry of await readdir(dir,{withFileTypes:true})) {
    const rel=prefix+entry.name;
    if (entry.isDirectory()) out.push(...await files(dir+'/'+entry.name,rel+'/'));
    else if (rel !== 'sw.js') out.push(rel);
  }
  return out.sort();
}
const assets=await files('dist');
const hash=createHash('sha256');
for(const file of assets) hash.update(await readFile('dist/'+file));
hash.update(await readFile('scripts/build.mjs'));
const version=hash.digest('hex').slice(0,12);
const mediaCode=(await readFile('dist/media.js','utf8')).replace('export async function', 'async function');
const worker=`// Generated by scripts/build.mjs. Cache changes whenever the app changes.
${mediaCode}
const PREFIX = 'deckforge-poc-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const CACHE = PREFIX + '${version}';
const ASSETS = ${JSON.stringify(assets.map(x=>'./'+x))};
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
// An update waits until all old app windows close: never reload an active round.
self.addEventListener('activate', event => event.waitUntil((async()=>{
  for (const name of await caches.keys()) if(name.startsWith(PREFIX) && name !== CACHE) await caches.delete(name);
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  if(event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith((async()=>{
    const cache = await caches.open(CACHE);
    const url = new URL(event.request.url);
    // Ignore query strings for the app shell, so cold launch works offline too.
    const path = url.pathname.endsWith('/') ? url.pathname + 'index.html' : url.pathname;
    const cached = await cache.match(path);
    if(cached) return url.pathname.endsWith('.wav') ? mediaResponse(cached, event.request.headers.get('Range')) : cached;
    try { return await fetch(event.request); }
    catch { if(event.request.mode === 'navigate') return await cache.match('./index.html'); throw new Error('Offline asset unavailable'); }
  })());
});
`;
await writeFile('dist/sw.js',worker);
console.log(`Built ${assets.length} offline assets; version ${version}`);
