import {validateCards,parseGameLines,gameLines,type GameCard} from './party-content.js';
import {esc,button} from './ui.js';
export function blankGameCard(kind:'quiz'|'survey'):GameCard{return {prompt:'',answers:[{text:'',aliases:[],points:1}],category:kind==='quiz'?'General':'Survey',points:1};}
export function validateGameDraft(card:GameCard,kind:'quiz'|'survey'):GameCard{return validateCards([card],kind)[0]!;}
export function gameCardFields(card:GameCard,kind:'quiz'|'survey'):string {
 return `<form id=game-card-form class=panel><h3>Edit Card</h3><label for=game-question>Question or prompt</label><textarea id=game-question required maxlength=300>${esc(card.prompt)}</textarea><label for=game-category>Category</label><input id=game-category maxlength=60 value="${esc(card.category)}">${kind==='quiz'?`<label for=game-points>Points</label><input id=game-points type=number min=1 max=1000 required value=${card.points}>`:''}${card.answers.map((answer,i)=>`<fieldset class=game-answer data-answer=${i}><legend>${kind==='quiz'?'Accepted answer':'Answer '+(i+1)}</legend><label for=game-answer-${i}>${kind==='quiz'?'Answer':'Answer text'}</label><input id=game-answer-${i} data-answer-text maxlength=120 required value="${esc(answer.text)}"><label for=game-aliases-${i}>Accepted alternatives · optional</label><textarea id=game-aliases-${i} data-answer-aliases placeholder="One alternative per line">${esc(answer.aliases.join('\n'))}</textarea><p class=muted>Up to 8 alternatives. The host can still accept other close answers during review.</p>${kind==='survey'?`<label for=game-answer-points-${i}>Answer points</label><input id=game-answer-points-${i} data-answer-points type=number min=1 max=1000 required value=${answer.points}><button type=button data-pack-action=remove-answer data-index=${i} ${card.answers.length===1?'disabled':''}>Remove Answer</button>`:''}</fieldset>`).join('')}${kind==='survey'?`<button type=button data-pack-action=add-answer ${card.answers.length>=8?'disabled':''}>＋ Add Answer</button>`:''}<div class=actions><button class=primary>Apply Card</button><button type=button data-pack-action=cancel-card>Cancel Card</button></div><p class=muted>Apply updates the draft. Choose Save Deck to keep your changes.</p></form>`;
}

export function bulkRoundtrips(cards:readonly GameCard[],kind:'quiz'|'survey'):boolean {
 if(!cards.length)return true;try{return JSON.stringify(parseGameLines(gameLines(cards,kind),kind))===JSON.stringify(cards);}catch{return false;}
}
