import {parseGameLines,gameLines,type GamePack} from './party-content.js';
import {savePacks,exportPacks,importPacks} from './game-pack-storage.js';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function mountPackEditor(root:HTMLElement,status:HTMLElement,initial:GamePack[],done:(packs:GamePack[])=>void,backLabel='Back to Link'):()=>void {
 const life=new AbortController();let packs=[...initial],editing:GamePack|undefined,busy=false;
 function render(){if(life.signal.aborted)return;root.innerHTML=`<section><div class=toolbar><h2>Game Decks</h2><button type=button data-pack-action=back>${esc(backLabel)}</button></div><p class=muted>Separate from your regular decks. Trivia decks also work with Team Trivia and Clue Board. Survey decks hold ranked answers and points.</p><div class=actions><button type=button data-pack-action=new-quiz>＋ Trivia Deck</button><button type=button data-pack-action=new-survey>＋ Survey Deck</button></div>${editing?`<form id=pack-form><label for=pack-name>Deck name</label><input id=pack-name required maxlength=80 value="${esc(editing.name)}"><label for=pack-lines>Cards · one per line</label><p class=muted>${editing.kind==='quiz'?'Question | Answer | alternatives separated by ; | Category | Points':'Question | Answer:points;alternative | Answer:points;alternative'}. Avoid literal | or ; inside text.</p><textarea id=pack-lines rows=12 required>${esc(gameLines(editing.cards,editing.kind))}</textarea><button class=primary>Save Deck</button><button type=button data-pack-action=cancel>Cancel</button><p class=muted>Edit, add, remove or move whole lines to edit/delete/reorder cards. Saving validates every line first.</p></form>`:`<div class=option-list>${packs.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<div class=row><button type=button data-pack-action=edit data-id="${esc(p.id)}">${esc(p.name)} · ${p.cards.length} ${p.kind==='survey'?'surveys':'questions'}</button><button type=button class=danger data-pack-action=delete data-id="${esc(p.id)}">Delete</button></div>`).join('')||'<p>No game decks yet. Create one above.</p>'}</div>`}<h3>Game Decks backup</h3><p class=muted>These decks have a separate backup. Regular library exports do not include them yet.</p><button type=button data-pack-action=export>Export Game Decks</button><label for=pack-import>Import Game Decks backup (adds copies)</label><input id=pack-import type=file accept=".json,application/json"></section>`;}
 root.addEventListener('click',event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-pack-action]');if(!button||busy)return;const action=button.dataset.packAction;
 if(action==='back'){done(packs);return;}if(action==='cancel'){editing=undefined;render();return;}if(action==='edit'){editing=structuredClone(packs.find(p=>p.id===button.dataset.id)!);render();return;}
 if(action==='new-quiz'||action==='new-survey'){const kind=action==='new-quiz'?'quiz':'survey';editing={id:crypto.randomUUID(),name:'',kind,cards:parseGameLines(kind==='quiz'?'What planet is known as the Red Planet? | Mars | | Space | 100':'Name a common pet | Dog:40;Canine | Cat:30;Kitten',kind)};render();return;}
 if(action==='export'){try{const blob=new Blob([exportPacks(packs)],{type:'application/json'}),url=URL.createObjectURL(blob),a=window.document.createElement('a');a.href=url;a.download='DeckForge-Game-Decks.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Save the downloaded file as your Game Decks backup.';}catch(e){status.textContent=String(e);}return;}
 if(action==='delete'){if(!button.dataset.confirm){button.dataset.confirm='yes';button.textContent='Tap again to delete';return;}const next=packs.filter(p=>p.id!==button.dataset.id);busy=true;void savePacks(next).then(()=>{if(life.signal.aborted)return;packs=next;render();status.textContent='Game deck deleted.';}).catch(e=>status.textContent=String(e)).finally(()=>busy=false);}
 },{signal:life.signal});
 root.addEventListener('submit',event=>{event.preventDefault();if(busy||!editing)return;try{const name=root.querySelector<HTMLInputElement>('#pack-name')!.value.trim();if(!name)throw new Error('Enter a deck name.');const nextPack={...editing,name,cards:parseGameLines(root.querySelector<HTMLTextAreaElement>('#pack-lines')!.value,editing.kind)},next=[...packs.filter(p=>p.id!==editing!.id),nextPack];busy=true;void savePacks(next).then(()=>{if(life.signal.aborted)return;packs=next;editing=undefined;render();status.textContent='Game deck saved locally.';}).catch(e=>status.textContent=String(e)).finally(()=>busy=false);}catch(e){status.textContent=String(e);}},{signal:life.signal});
 root.addEventListener('change',event=>{const el=event.target as HTMLInputElement;if(el.id!=='pack-import'||busy)return;const file=el.files?.[0];if(!file)return;busy=true;void(async()=>{try{if(file.size>5*1024*1024)throw new Error('Use a file smaller than 5 MB.');const additions=importPacks(await file.text()),next=[...packs,...additions];await savePacks(next);if(life.signal.aborted)return;packs=next;render();status.textContent=`Added ${additions.length} independent game decks.`;}catch(e){status.textContent=String(e);}finally{busy=false;}})();},{signal:life.signal});
 render();return ()=>life.abort();
}
