import {validateCards,type GamePack} from './party-content.js';
// Independent local store: existing regular/Taboo deck backups remain unchanged.
let database:Promise<IDBDatabase>|undefined;
function open(){return database??=new Promise((resolve,reject)=>{const req=indexedDB.open('deckforge-game-packs',1);req.onupgradeneeded=()=>req.result.createObjectStore('packs');req.onerror=()=>{database=undefined;reject(req.error);};req.onblocked=()=>{database=undefined;reject(new Error('Close other app windows and reopen.'));};req.onsuccess=()=>{req.result.onversionchange=()=>{req.result.close();database=undefined;};resolve(req.result);};});}
export function decodePacks(value:unknown):GamePack[]{if(!Array.isArray(value)||value.length>200)throw new Error('Use up to 200 game decks.');const ids=new Set<string>();return value.map(p=>{if(!p||typeof p!=='object'||typeof p.id!=='string'||!p.id||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim()||p.name.length>80||(p.kind!=='quiz'&&p.kind!=='survey'))throw new Error('Invalid game deck.');ids.add(p.id);return {id:p.id,name:p.name.trim(),kind:p.kind,cards:validateCards(p.cards,p.kind)};});}
export async function loadPacks():Promise<GamePack[]>{const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('packs','readonly'),req=tx.objectStore('packs').get('library');tx.oncomplete=()=>{try{resolve(req.result===undefined?[]:decodePacks(req.result));}catch(e){reject(e);}};tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
export async function savePacks(packs:GamePack[]):Promise<void>{const valid=decodePacks(packs),db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('packs','readwrite');tx.objectStore('packs').put(valid,'library');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
export function exportPacks(packs:GamePack[]){return JSON.stringify({format:'deckforge-game-decks',version:1,packs:decodePacks(packs)},null,2);}
export function importPacks(text:string):GamePack[]{if(new TextEncoder().encode(text).byteLength>5*1024*1024)throw new Error('Use a file smaller than 5 MB.');const data=JSON.parse(text);if(data?.format!=='deckforge-game-decks'||data.version!==1)throw new Error('Choose a Game Decks backup.');return decodePacks(data.packs).map(p=>({...p,id:crypto.randomUUID()}));}
