import {libraryQuiz,libraryQuizNote,type QuizDeck} from './library-quiz.js';
import {partyUI,type PartyView} from './party-ui.js';
import {PARTY_MODES,type GamePack,type GameCard} from './party-content.js';
import {loadPacks} from './game-pack-storage.js';
import {mountPackEditor} from './game-pack-editor.js';
import {roomRequest} from './room-transport.js';
import {credentials,remember,remove,type Credential} from './room-session.js';
import {categoryKey,categoryPool,readCategoryDecks,drawCategories,type CategoryDeck} from './category-source.js';
interface CategoryState {usedCategories?:string[];stage:string;config:{items:string[];seconds:number;letter:string};letter:string;deadline:number;own:{answers:string[];revision:number};submitted:number;review:null|{id:string;answers:{category:string;text:string;invalid:boolean;decision:string;automaticReason:string;reason:string;points:number}[]}[];totals:Record<string,number>}
interface Snapshot {party?:PartyView;game?:string;serverNow:number;categories?:CategoryState;code:string;phase:'lobby'|'voting'|'revealed';round:number;host:boolean;ownVote:string|null;expiresAt:number;players:{id:string;name:string;connected:boolean;voted:boolean}[];totals:{cats:number;dogs:number}|null}
export function mountMultiplayer(root:HTMLElement,status:HTMLElement,decks:CategoryDeck[],quizDecks:readonly QuizDeck[]=[],openDeckManager?:()=>void):()=>void {
 const libraryQuizzes=quizDecks.map(libraryQuiz);
 const lifecycle=new AbortController();
 const intervals:number[]=[];
 const timeouts:number[]=[];
 const setInterval=(callback:()=>void,ms:number)=>{const id=window.setInterval(callback,ms);intervals.push(id);return id;};
 const setTimeout=(callback:()=>void,ms:number)=>{const id=window.setTimeout(callback,ms);timeouts.push(id);return id;};
 const listen=(target:EventTarget,type:string,handler:(event:Event)=>void)=>target.addEventListener(type,handler,{signal:lifecycle.signal});
 const document={querySelector:<T extends Element=Element>(selector:string)=>root.querySelector<T>(selector),querySelectorAll:<T extends Element=Element>(selector:string)=>root.querySelectorAll<T>(selector),get hidden(){return window.document.hidden;},addEventListener:(type:string,handler:()=>void)=>listen(window.document,type,handler)};

let session:Credential|undefined,saved:Credential[]=[],paused=false,generation=0;
try{session=credentials(JSON.parse(sessionStorage.getItem('deckforge-link-session')??'null'))[0];saved=credentials(JSON.parse(sessionStorage.getItem('deckforge-link-rooms')??'[]'));if(session)saved=remember(saved,session);paused=sessionStorage.getItem('deckforge-link-paused')==='yes';}catch{}
const invitedCode=new URL(location.href).searchParams.get('room')?.toUpperCase();
if(invitedCode&&session?.code!==invitedCode)paused=true;
let current:Snapshot|undefined,busy=false,polling=false;
let tvLink='',tvLinkCode='';
let packs:GamePack[]=[],editorOpen=false,packsLoaded=false,stopEditor:(()=>void)|undefined,packError='';
void loadPacks().then(value=>{if(lifecycle.signal.aborted)return;packs=value;packsLoaded=true;if(!editorOpen)render();}).catch(e=>{packError=String(e);});
function openPacks(){if(openDeckManager){openDeckManager();return;}if(!packsLoaded&&!packError){status.textContent='Game Decks are loading. Try again in a moment.';return;}if(packError){status.textContent=packError;return;}editorOpen=true;stopEditor=mountPackEditor(root,status,packs,value=>{packs=value;stopEditor?.();stopEditor=undefined;editorOpen=false;render();});}
let partyDraft='',partyRevision=0,partyKey='',partyDirty=false,partySaving=false,partyTimer:number|undefined;
function initParty(s:Snapshot){const g=s.party;if(!g)return;const key='deckforge-link-party:'+s.code+':'+s.round+':'+g.ownId;if(key===partyKey)return;partyKey=key;partyDraft=g.own.text;partyRevision=g.own.revision;partyDirty=false;try{const v=JSON.parse(sessionStorage.getItem(key)??'null');if(v&&typeof v.text==='string'&&v.text.length<=300&&Number.isSafeInteger(v.revision)&&v.revision>partyRevision){partyDraft=v.text;partyRevision=v.revision;partyDirty=true;}}catch{}}
async function saveParty(){const g=current?.party;if(!partyDirty||partySaving||!session||paused||!g?.canAnswer||g.delivery!=='phones'||g.stage!=='answering')return;const round=current!.round,turn=generation,text=partyDraft,revision=partyRevision;partySaving=true;try{const r=await api('party-save',{round,text,revision});if(turn===generation&&current?.round===round){partyDirty=partyRevision!==revision;accept(r);const el=document.querySelector('#party-save-state');if(el)el.textContent=partyDirty?'Saving…':'Answer saved';}}catch(e){if(turn===generation){const el=document.querySelector('#party-save-state');if(el)el.textContent='Not saved · '+String(e);}}finally{partySaving=false;if(partyDirty&&turn===generation&&current?.round===round)setTimeout(()=>void saveParty(),2000);}}
function partyClock(){const g=current?.party,el=document.querySelector('#party-clock');if(!g||!el)return;const seconds=Math.max(0,Math.ceil((g.deadline-Date.now()-clockOffset)/1000));el.textContent=seconds?Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):'Time is up';const input=document.querySelector<HTMLInputElement>('#party-answer');if(input)input.disabled=seconds===0;}
function shuffled<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j]!,result[i]!];}return result;}
async function partyAction(action:string,control:HTMLButtonElement){if(action==='party-decks'){openPacks();return;}if(!current?.party)return;const data:Record<string,unknown>={round:current.round};const value=(id:string)=>document.querySelector<HTMLInputElement|HTMLSelectElement>('#'+id)?.value??'';
 if(action==='party-start'){const g=current.party,id=value('party-pack');let cards:GameCard[];if(g.mode==='wheel'){const deck=decks.find(d=>d.id===id);if(!deck)throw new Error('Choose a phrase deck.');cards=shuffled(deck.items.map(prompt=>({prompt,category:deck.name.slice(0,60),points:1,answers:[{text:prompt,aliases:[],points:1}]}))).slice(0,25);}else if(g.mode==='trivia'&&id.startsWith('library:')){const source=libraryQuizzes.find(p=>p.id===id.slice(8));if(!source?.cards.length)throw new Error('Choose a library deck with usable questions and backs.');cards=shuffled(source.cards).slice(0,25);}else{const pack=packs.find(p=>p.id===(g.mode==='trivia'&&id.startsWith('pack:')?id.slice(5):id));if(!pack)throw new Error('Choose a game deck.');cards=(g.mode==='jeopardy'?[...pack.cards]:shuffled(pack.cards)).slice(0,25);}Object.assign(data,{cards,hostPlaying:document.querySelector<HTMLInputElement>('#party-playing')!.checked,delivery:value('party-delivery'),seconds:Number(value('party-duration'))});}
 if(action==='party-select'||action==='party-board-reveal')data.index=Number(control.dataset.index);
 if(action==='party-mark'){data.player=control.dataset.player;data.automatic=control.dataset.auto==='true';data.points=Number(document.querySelector<HTMLInputElement>('[data-party-points="'+control.dataset.player+'"]')?.value??0);}
 if(action==='party-letter')data.letter=value('party-letter');if(action==='party-solve')data.text=value('party-solution');if(action==='party-spoken-solve')data.correct=control.dataset.correct==='true';
 generation++;busy=true;control.disabled=true;try{accept(await api(action,data));}finally{busy=false;control.disabled=false;}}

let entryMode:'create'|'join'|undefined=new URL(location.href).searchParams.has('room')?'join':undefined;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const btn=(action:string,text:string,cls='')=>`<button type="button" data-action="${action}" class="${cls}">${text}</button>`;
function tvLinkMarkup(){return tvLink&&tvLinkCode===current?.code?`<p class=muted>Open this on the Mac or spare device you will mirror. Public Trivia information only; no player slot is used. Anyone with this link can see the audience screen.</p><label for=tv-url>TV link</label><input id=tv-url readonly value="${esc(tvLink)}"><a href="${esc(tvLink)}" target=_blank rel=noopener>Open TV View</a>${btn('tv-new','Replace TV Link')}<p class=muted>Replacing the link disconnects the previous display.</p>`:'';}
function persist(){try{sessionStorage.setItem('deckforge-link-rooms',JSON.stringify(saved));sessionStorage.setItem('deckforge-link-paused',paused?'yes':'no');if(session)sessionStorage.setItem('deckforge-link-session',JSON.stringify(session));else sessionStorage.removeItem('deckforge-link-session');}catch{status.textContent='Room recovery is unavailable because browser storage is full. Keep this screen open.';}}
function forget(message='Room ended or expired.'){if(session){const code=session.code;saved=remove(saved,code);try{sessionStorage.removeItem('deckforge-link-source:'+code);for(const key of Object.keys(sessionStorage))if(key.startsWith('deckforge-link-draft:'+code+':')||key.startsWith('deckforge-link-party:'+code+':'))sessionStorage.removeItem(key);}catch{}}session=undefined;current=undefined;generation++;persist();render();status.textContent=message;}

let draft:string[]=[],revision=0,draftKey='',saving=false,dirty=false,saveTimer:ReturnType<typeof setTimeout>|undefined,clockOffset=0;
function initializeDraft(s:Snapshot){const g=s.categories;if(!g)return;const key='deckforge-link-draft:'+s.code+':'+s.round;if(key===draftKey)return;draftKey=key;draft=[...g.own.answers];revision=g.own.revision;dirty=false;try{const local=JSON.parse(sessionStorage.getItem(key)??'null');if(local&&Array.isArray(local.answers)&&local.answers.length===draft.length&&local.answers.every((a:unknown)=>typeof a==='string'&&a.length<=80)&&Number.isSafeInteger(local.revision)&&local.revision>revision){draft=local.answers;revision=local.revision;dirty=true;}}catch{}}
function clock(){partyClock();const g=current?.categories,el=document.querySelector('#clock');if(!g||!el)return;const seconds=Math.max(0,Math.ceil((g.deadline-Date.now()-clockOffset)/1000));el.textContent=g.stage==='locked'?'Locked':seconds?Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0'):'Time is up';document.querySelectorAll<HTMLInputElement>('[data-answer]').forEach(i=>i.disabled=seconds===0||g.stage!=='writing');}
async function saveDraft(){if(!dirty||saving||!session||paused||current?.categories?.stage!=='writing')return;const turn=generation,code=session.code,round=current.round,answers=[...draft],rev=revision;saving=true;try{const result=await api('cat-save',{round,answers,revision:rev});if(turn===generation&&current?.round===round){dirty=revision!==rev;accept(result);const el=document.querySelector('#save-state');if(el)el.textContent=dirty?'Saving…':'Answers saved';}}catch(e){if(turn===generation){const el=document.querySelector('#save-state');if(el)el.textContent='Not saved · '+String(e);}}finally{saving=false;if(dirty&&session?.code===code&&current?.round===round&&turn===generation)setTimeout(()=>void saveDraft(),2000);}}
let importedDecks:CategoryDeck[]=decks,selectedPool:CategoryDeck|undefined,sourceMode='manual',sourceCode='';
function sourceKey(){return 'deckforge-link-source:'+session?.code;}
function rememberSource(){try{sessionStorage.setItem(sourceKey(),JSON.stringify({mode:sourceMode,pool:selectedPool}));}catch{status.textContent='Category pool works in this tab, but browser storage is full. Export your original deck for backup.';}}
function restoreSource(code:string){if(sourceCode===code)return;sourceCode=code;sourceMode='manual';selectedPool=undefined;try{const value=JSON.parse(sessionStorage.getItem('deckforge-link-source:'+code)??'null');if(value?.pool&&typeof value.pool.name==='string'){selectedPool={id:String(value.pool.id),name:value.pool.name,items:categoryPool(value.pool.items)};sourceMode=value.mode==='deck'?'deck':'manual';}}catch{}}
function sourceUI(g:CategoryState){return `<label for=category-source>Category source</label><select id=category-source><option value=manual ${sourceMode==='manual'?'selected':''}>Enter categories manually</option><option value=deck ${sourceMode==='deck'?'selected':''}>Draw from a deck</option></select><div id=deck-source ${sourceMode==='deck'?'':'hidden'}><p class=muted>Choose a deck from your library. Only the selected round categories are shared; the rest of your deck stays on this device.</p><label for=category-deck>Deck</label><select id=category-deck>${selectedPool?`<option value=selected>${esc(selectedPool.name)} · ${selectedPool.items.length} categories</option>`:'<option value="">Choose a deck</option>'}${importedDecks.map((d,i)=>`<option value="import-${i}">${esc(d.name)} · ${d.items.length} cards</option>`).join('')}</select><p id=pool-state class=muted></p>${btn('draw-categories','Draw Categories')}${btn('reset-pool','Reset Used Categories')}<p class=muted>Up to 12 unused categories each round. A shorter round uses the remaining items. Reset explicitly to allow repeats.</p></div>`;}
function fillDraw(){const g=current?.categories;if(!g)return;const area=document.querySelector<HTMLTextAreaElement>('#categories'),info=document.querySelector('#pool-state'),start=document.querySelector<HTMLButtonElement>('[data-action=cat-start]');if(sourceMode==='manual'){if(area)area.readOnly=false;if(start)start.disabled=false;return;}const items=selectedPool?drawCategories(selectedPool.items,g.usedCategories??[]):[];if(area){area.readOnly=true;area.value=items.join('\n');}if(start)start.disabled=!items.length;if(info)info.textContent=selectedPool?`${selectedPool.items.filter(x=>!(g.usedCategories??[]).includes(categoryKey(x))).length} unused of ${selectedPool.items.length}. ${items.length?items.length+' selected for the next round.':'Pool exhausted. Reset used categories to continue.'}`:'Choose a deck to draw categories.';}
listen(root,'change',event=>{if(editorOpen)return;const el=event.target as HTMLInputElement|HTMLSelectElement;if(el.id==='party-team'){if(!el.value||busy)return;generation++;busy=true;void api('party-team',{team:el.value}).then(r=>{current=undefined;accept(r);}).catch(e=>status.textContent=String(e)).finally(()=>busy=false);return;}if(el.id==='category-source'){sourceMode=el.value;rememberSource();const section=document.querySelector<HTMLElement>('#deck-source');if(section)section.hidden=sourceMode!=='deck';fillDraw();}else if(el.id==='category-deck'){if(el.value.startsWith('import-')){const d=importedDecks[Number(el.value.slice(7))];try{if(d)selectedPool={...d,items:categoryPool(d.items)};rememberSource();fillDraw();}catch(e){status.textContent=String(e);el.value=selectedPool?'selected':'';}}}else if(el.id==='deck-backup'){const file=(el as HTMLInputElement).files?.[0];if(!file)return;const code=current?.code;void(async()=>{try{if(file.size>20*1024*1024)throw new Error('Choose a backup smaller than 20 MB.');const decks=readCategoryDecks(await file.text());if(current?.code!==code)return;importedDecks=decks;const picker=document.querySelector<HTMLSelectElement>('#category-deck');if(picker)picker.innerHTML=(selectedPool?`<option value=selected>${esc(selectedPool.name)}</option>`:'<option value="">Choose a deck</option>')+decks.map((d,i)=>`<option value="import-${i}">${esc(d.name)} · ${d.items.length} cards</option>`).join('');status.textContent='Backup read locally. Choose a deck to use as categories.';}catch(e){status.textContent=String(e);}})();}});

function categoriesUI(s:Snapshot){const g=s.categories!;
 if(g.stage==='lobby')return `<section><h2>Categories</h2><p>Write an answer for each category starting with the shared letter. Unique valid answers earn 1 point.</p>${s.host?`${sourceUI(g)}<label for=categories>Categories · one per line (up to 12)</label><textarea id=categories rows=12 maxlength=731>${esc(g.config.items.join('\n'))}</textarea><label for=duration>Round length</label><select id=duration>${[60,120,180,300].map(n=>`<option value=${n} ${n===g.config.seconds?'selected':''}>${n/60} minutes</option>`).join('')}</select><label for=letter>Letter (leave blank for Random)</label><input id=letter maxlength=1 value="${esc(g.config.letter)}" autocapitalize=characters>${btn('cat-start','Start Round','primary')}`:`<p>Waiting for the host. ${g.config.items.length} categories · ${g.config.seconds/60} minutes.</p>`}</section>`;
 if(g.stage==='writing'||g.stage==='locked')return `<section><div class=round-heading><h2>Letter <strong>${esc(g.letter)}</strong></h2><strong id=clock></strong></div><p class=muted>Round ${s.round} · Answers stay private until reveal.</p>${g.config.items.map((item,i)=>`<label for=answer-${i}>${i+1}. ${esc(item)}</label><input id=answer-${i} data-answer=${i} maxlength=80 autocomplete=off value="${esc(draft[i]??'')}" ${g.stage==='locked'?'disabled':''}>`).join('')}<p id=save-state class=muted>${g.stage==='locked'?'Answers locked. Only answers received before the deadline count.':dirty?'Saving…':'Answers saved'}</p>${s.host?(g.stage==='writing'?btn('cat-lock','Finish Early'):btn('cat-reveal','Reveal Answers','primary')):''}</section>`;
 const rows=g.review??[];
 return `<section><h2>${g.stage==='scored'?'Scores':'Review Answers'} · ${esc(g.letter)}</h2><p class=muted>Exact duplicates, common singular/plural forms and close spelling matches are automatically excluded. The host can override any nonblank answer.</p><ul class=scoreboard>${rows.map(row=>`<li><strong>${esc(s.players.find(p=>p.id===row.id)?.name??'Player')}</strong> · ${row.answers.reduce((n,a)=>n+a.points,0)} this round${g.stage==='scored'?` · ${g.totals[row.id]??0} total`:''}</li>`).join('')}</ul>${g.config.items.map((category,i)=>`<article class=category-review><h3>${i+1}. ${esc(category)}</h3>${rows.map(row=>{const a=row.answers[i]!;return `<div class="review-answer ${a.points?'accepted':'excluded'}"><small>${esc(s.players.find(p=>p.id===row.id)?.name??'Player')}</small><p><strong>${esc(a.text||'—')}</strong></p><small>${a.points?'1 point':'Excluded · 0 points'} · ${esc(a.reason)}${a.decision!=='auto'&&a.automaticReason?' (automatic: '+esc(a.automaticReason)+')':''}</small>${s.host&&g.stage==='review'?`<label for="decision-${row.id}-${i}" class=muted>Host ruling</label><select id="decision-${row.id}-${i}" data-player="${esc(row.id)}" data-index=${i}><option value=auto ${a.decision==='auto'?'selected':''}>Automatic scoring</option><option value=allow ${a.decision==='allow'?'selected':''} ${!a.text.trim()?'disabled':''}>Allow point</option><option value=reject ${a.decision==='reject'?'selected':''}>Exclude answer</option></select>`:''}</div>`;}).join('')}</article>`).join('')}${s.host?btn(g.stage==='review'?'cat-finalize':'cat-next',g.stage==='review'?'Finalize Scores':'Next Round','primary'):''}</section>`;

}
listen(root,'input',event=>{if(editorOpen)return;const el=event.target as HTMLInputElement;if(el.id==='party-answer'){partyDraft=el.value;partyRevision++;partyDirty=true;try{sessionStorage.setItem(partyKey,JSON.stringify({text:partyDraft,revision:partyRevision}));}catch{}const label=document.querySelector('#party-save-state');if(label)label.textContent='Saving…';clearTimeout(partyTimer);partyTimer=setTimeout(()=>void saveParty(),650);return;}if(el.dataset.answer===undefined)return;draft[Number(el.dataset.answer)]=el.value;revision++;dirty=true;try{sessionStorage.setItem(draftKey,JSON.stringify({answers:draft,revision}));}catch{}const label=document.querySelector('#save-state');if(label)label.textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>void saveDraft(),650);});
listen(root,'change',event=>{const el=event.target as HTMLSelectElement;if(!el.dataset.player||busy)return;generation++;busy=true;void api('cat-mark',{round:current?.round,player:el.dataset.player,index:Number(el.dataset.index),decision:el.value}).then(r=>{current=undefined;accept(r);}).catch(e=>{status.textContent=String(e);render();}).finally(()=>busy=false);});

function updateLibraryQuizNote(){const picker=document.querySelector<HTMLSelectElement>('#party-pack'),note=document.querySelector('#party-library-note');if(!picker||!note)return;const source=picker.value.startsWith('library:')?libraryQuizzes.find(p=>p.id===picker.value.slice(8)):undefined;note.textContent=source?libraryQuizNote(source):'Library decks use Front as the question and Back as the answer. Add backs in Decks; no Flashcards assignment is required. Questions over 300 characters, answers over 120 characters and missing backs are skipped. Only up to 25 selected question/answer pairs are sent to this room.';}
listen(root,'change',event=>{if((event.target as HTMLElement).id==='party-pack')updateLibraryQuizNote();});
function render(){
 if(editorOpen||lifecycle.signal.aborted)return;
 if(!current){root.innerHTML=`<p class="muted">Play together from separate devices. Choose a game and create a room, or join with a room code.</p>${saved.length?`<section><h2>Resume a Room</h2><p class="muted">Use this same tab to keep your role and answers, even after a round starts.</p>${saved.map(c=>`<button data-action="resume" data-code="${esc(c.code)}">Resume ${esc(c.code)}</button>`).join('')}</section>`:''}${!entryMode?`<div class="actions">${btn('choose-create','Create Room','primary')}${btn('choose-join','Join Room')}</div>`:`<form id="join-form"><label for="nickname">Temporary nickname</label><input id="nickname" name="nickname" maxlength="24" autocomplete="off" required>${entryMode==='join'?`<label for="code">Room code</label><input id="code" name="code" value="${esc(new URL(location.href).searchParams.get('room')??'')}" maxlength="8" autocapitalize="characters" autocomplete="off">`:''}<div ${entryMode==='join'?'hidden':''}><label for="game">Mode</label><select id="game"><option value="categories">Categories</option>${Object.entries(PARTY_MODES).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></div><div class="actions"><button name="${entryMode}" class="primary">${entryMode==='create'?'Create Room':'Join Room'}</button>${btn('choose-back','Back')}</div></form>`}${openDeckManager?'':btn('party-decks','Game Decks')}<p class="muted">Up to 12 players. Internet required. No accounts. Deck libraries stay local.</p>`;return;}
 const setup=current.party?.stage==='lobby'?['party-pack','party-team','party-delivery','party-duration','party-playing'].map(id=>{const el=document.querySelector<HTMLInputElement>('#'+id);return el?{id,value:el.value,checked:el.checked}:null;}).filter(x=>x!==null):[];
 const s=current,link=location.origin+location.pathname+'?room='+s.code;
 root.innerHTML=`<section><p class="muted">${s.host?'YOU ARE THE HOST':(s.party?PARTY_MODES[s.party.mode]:(s.game==='categories'?'CATEGORIES':'VOTE TEST'))} · Round ${s.round}</p><h2>Room ${esc(s.code)}</h2><label for="join-link">Join link</label><input id="join-link" readonly value="${esc(link)}">${btn('copy','Copy Join Link')}${s.host&&s.party?.mode==='trivia'?btn('tv-link','TV View Link'):''}<div id=tv-link-panel>${tvLinkMarkup()}</div><p id="room-summary" class="muted">${s.players.length} players · expires at ${esc(new Date(s.expiresAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}))}</p></section>${s.party?partyUI({...s,party:{...s.party,own:{text:partyDraft,revision:partyRevision}}},packs,decks,libraryQuizzes):s.categories?categoriesUI(s):`<section><h2>Cats or dogs?</h2>${s.phase==='lobby'?`<p>Waiting for the host to start.</p>${s.host?btn('start','Start Vote','primary'):''}`:s.phase==='voting'?`<div class="actions">${btn('cats',`Cats ${s.ownVote==='cats'?'✓':''}`,'primary')}${btn('dogs',`Dogs ${s.ownVote==='dogs'?'✓':''}`,'primary')}</div><p>${s.ownVote?'Your vote is saved. You may change it until reveal.':'Choose privately.'} ${s.players.filter(p=>p.voted).length} of ${s.players.length} voted.</p>${s.host?btn('reveal','Reveal Results'):''}`:`<p class="totals">Cats ${s.totals?.cats} · Dogs ${s.totals?.dogs}</p>${s.host?btn('lobby','Back to Lobby'):''}`}</section>`}<section><h2>Players</h2><ul id="players">${s.players.map(p=>`<li>${esc(p.name)} <small>${p.connected?'Connected':'Away'}${p.voted?(s.categories?' · Saved':' · Voted'):''}</small></li>`).join('')}</ul></section><div class="actions">${s.host?btn('end','End Room for Everyone','danger'):''}${btn('leave','Leave Temporarily')}</div>`;for(const saved of setup){const el=document.querySelector<HTMLInputElement>('#'+saved.id);if(el){el.value=saved.value;if(saved.id==='party-playing')el.checked=saved.checked;}}updateLibraryQuizNote();clock();if(s.categories?.stage==='lobby'&&s.host)fillDraw();
}
async function api(action:string,data:unknown={},code=session?.code,secret=session?.token){
 const {response,body}=await roomRequest<{state:Snapshot;token?:string;error?:string}>(action,data,code,secret,lifecycle.signal);if(!response.ok){if((response.status===410||response.status===401)&&session?.code===code&&session?.token===secret)forget(body.error);throw new Error(body.error??'Request failed.');}return body;
}
function accept(result:{state:Snapshot;token?:string}){
 if(lifecycle.signal.aborted)return;
 if(result.token){session={code:result.state.code,token:result.token};saved=remember(saved,session);paused=false;persist();}
 const previous=current,next=result.state;clockOffset=next.serverNow-Date.now();initializeDraft(next);initParty(next);restoreSource(next.code);const partyStable=previous?.code===next.code&&previous.round===next.round&&!!next.party&&JSON.stringify({...previous.party,own:next.party.canAnswer?null:previous.party?.own})===JSON.stringify({...next.party,own:next.party.canAnswer?null:next.party.own});const stable=partyStable||previous?.code===next.code&&previous.round===next.round&&previous.categories?.stage===next.categories?.stage&&(['lobby','writing','locked'].includes(next.categories?.stage??'')||(['review','scored'].includes(next.categories?.stage??'')&&JSON.stringify(previous?.categories?.review)===JSON.stringify(next.categories?.review)&&JSON.stringify(previous?.categories?.totals)===JSON.stringify(next.categories?.totals))); const changed=JSON.stringify(previous)!==JSON.stringify(next);current=next;if(changed&&!stable)render();if(stable){const summary=document.querySelector('#room-summary');if(summary)summary.textContent=next.players.length+' players · expires at '+new Date(next.expiresAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});const list=document.querySelector('#players');if(list)list.innerHTML=next.players.map(p=>`<li>${esc(p.name)} <small>${p.connected?'Connected':'Away'}${p.voted?' · Saved':''}</small></li>`).join('');}clock();if(dirty&&!saving)void saveDraft();if(partyDirty&&!partySaving)void saveParty();status.textContent='Connected · updates about every 2 seconds';
}
listen(root,'submit',event=>{if(editorOpen)return;event.preventDefault();const form=event.target as HTMLFormElement,submit=(event as SubmitEvent).submitter as HTMLButtonElement;if(busy)return;generation++;busy=true;
 void(async()=>{try{const name=(form.elements.namedItem('nickname') as HTMLInputElement).value;const creating=submit.name==='create';const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const code=creating?Array.from(crypto.getRandomValues(new Uint8Array(8)),n=>alphabet[n%32]).join(''):(form.elements.namedItem('code') as HTMLInputElement).value.trim().toUpperCase();if(!/^[A-Z2-9]{8}$/.test(code))throw new Error('Enter the 8-character room code.');accept(await api(creating?'create':'join',{name,game:(document.querySelector('#game') as HTMLSelectElement).value},code,''));}catch(e){status.textContent=String(e);}finally{busy=false;}})();});
listen(root,'click',event=>{if(editorOpen)return;const control=(event.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!control||busy)return;const rawAction=control.dataset.action!;if(rawAction.startsWith('party-')){void partyAction(rawAction,control).catch(e=>status.textContent=String(e));return;}const confirmed=rawAction.endsWith('-confirm');const action=confirmed?rawAction.slice(0,-8):rawAction;
 if(action==='tv-link'||action==='tv-new'){
  if(action==='tv-new'&&!confirmed){control.textContent='Tap again to disconnect the old display';control.dataset.action='tv-new-confirm';return;}
  if(action==='tv-link'&&tvLink&&tvLinkCode===current?.code){const panel=document.querySelector('#tv-link-panel');if(panel)panel.innerHTML=tvLinkMarkup();return;}
  const code=current?.code;if(!code)return;busy=true;
  void roomRequest<{displayToken?:string;error?:string}>('audience-enable',{},code,session?.token,lifecycle.signal).then(({response,body})=>{
   if(lifecycle.signal.aborted||current?.code!==code)return;
   if(!response.ok||!body.displayToken)throw new Error(body.error??'Could not create TV link.');
   const url=new URL(location.origin+location.pathname);url.searchParams.set('tv',code);url.hash=new URLSearchParams({display:body.displayToken}).toString();tvLink=url.href;tvLinkCode=code;
   const panel=document.querySelector('#tv-link-panel');if(panel)panel.innerHTML=tvLinkMarkup();
  }).catch(e=>status.textContent=String(e)).finally(()=>busy=false);return;
 }
 if(action.startsWith('choose-')){entryMode=action==='choose-create'?'create':action==='choose-join'?'join':undefined;render();return;}
 if(action==='leave'){generation++;paused=true;current=undefined;persist();render();status.textContent='Left temporarily. Resume this room from the same tab. Other players can continue; the room still expires normally.';return;}
 if(action==='resume'){const found=saved.find(c=>c.code===control.dataset.code);if(!found)return;generation++;session=found;paused=false;persist();busy=true;void api('state').then(accept).catch(e=>status.textContent=String(e)).finally(()=>busy=false);return;}
 if(action==='copy'){const link=(document.querySelector('#join-link') as HTMLInputElement).value;void navigator.clipboard.writeText(link).then(()=>status.textContent='Join link copied.').catch(()=>status.textContent='Select and copy the join link above.');return;}
 if(action==='draw-categories'){fillDraw();return;}
 if(action==='reset-pool'){if(!confirmed){control.textContent='Tap again to allow category repeats';control.dataset.action='reset-pool-confirm';return;}generation++;busy=true;void api('cat-reset-pool',{round:current?.round}).then(r=>{accept(r);fillDraw();control.dataset.action='reset-pool';control.textContent='Reset Used Categories';}).catch(e=>status.textContent=String(e)).finally(()=>busy=false);return;}
 if(action==='cat-lock'&&!confirmed){control.textContent='Tap again to lock everyone’s answers';control.dataset.action='cat-lock-confirm';return;}
 if(action==='end'&&!confirm('End this room for everyone?'))return;
 generation++;busy=true;control.disabled=true;void(async()=>{try{if(action==='end'){await api('end');forget();status.textContent='Room ended and deleted.';}else accept(await api(action==='cats'||action==='dogs'?'vote':action,{choice:action,round:current?.round,...(action==='cat-start'?{config:{items:(document.querySelector('#categories') as HTMLTextAreaElement).value.split('\n').map(x=>x.trim()).filter(Boolean),seconds:Number((document.querySelector('#duration') as HTMLSelectElement).value),letter:(document.querySelector('#letter') as HTMLInputElement).value,source:sourceMode}}:{})}));}catch(e){status.textContent=String(e);}finally{busy=false;control.disabled=false;}})();
});
async function poll(){if(editorOpen||!session||paused||busy||polling||document.hidden||lifecycle.signal.aborted)return;if(lifecycle.signal.aborted)return;const turn=generation;polling=true;try{const result=await api('state');if(turn===generation&&!paused)accept(result);}catch(e){if(turn===generation)status.textContent=String(e)+(session?' · reconnecting when online':'');}finally{polling=false;}}
setInterval(clock,200);setInterval(()=>void poll(),2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void poll();});listen(window,'online',()=>void poll());render();void poll();

 return ()=>{stopEditor?.();clearTimeout(partyTimer);generation++;paused=true;lifecycle.abort();for(const id of intervals)window.clearInterval(id);for(const id of timeouts)window.clearTimeout(id);clearTimeout(saveTimer);};
}