import {PARTY_MODES,type GamePack,type PartyMode,type AcceptedAnswer} from './party-content.js';
export interface PartyView {selfId:string;participants:string[];livePoints:Record<string,number>;mode:PartyMode;stage:string;hostPlaying:boolean;delivery:string;seconds:number;deadline:number;index:number;count:number;question:string;category:string;points:number;own:{text:string;revision:number};canAnswer:boolean;ownId:string;totals:Record<string,number>;teams:Record<string,string>;board:{index:number;category:string;points:number;used:boolean}[];review:{id:string;text:string;points:number;automatic:number;decision:number|null}[]|null;key:AcceptedAnswer[]|null;revealed:number[];strikes:number;letters:string[];puzzle:string;turnId:string|null;spin:number|null;canControl:boolean}
export interface PartySnapshot {host:boolean;round:number;players:{id:string;name:string}[];party:PartyView}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(action:string,label:string,extra='',primary=false)=>`<button type=button data-action="party-${action}" ${extra} class="${primary?'primary':''}">${label}</button>`;
export function partyUI(s:PartySnapshot,packs:GamePack[],decks:{id:string;name:string}[]):string{
 const g=s.party,team=g.mode==='team-trivia'||g.mode==='survey',name=(id:string)=>s.players.find(p=>p.id===id)?.name??id;
 const scoreboard=Object.entries(g.totals).map(([id,n])=>`<li>${esc(name(id))}: <strong>${n}</strong></li>`).join('');
 if(g.stage==='lobby')return `<section><h2>${PARTY_MODES[g.mode]}</h2>${team?`<label for=party-team>Your team</label><select id=party-team><option value="">Choose a team</option>${[1,2,3,4].map(n=>`<option ${g.teams[g.selfId]==='Team '+n?'selected':''}>Team ${n}</option>`).join('')}</select><p class=muted>First playing person to join each team is its captain and submits the shared answer.</p><ul>${s.players.map(p=>`<li>${esc(p.name)} · ${esc(g.teams[p.id]??'Choose a team')}</li>`).join('')}</ul>`:''}${s.host?`<label for=party-pack>${g.mode==='wheel'?'Phrase deck':'Game deck'}</label><select id=party-pack><option value="">Choose a deck</option>${(g.mode==='wheel'?decks:packs.filter(p=>p.kind===(g.mode==='survey'?'survey':'quiz'))).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select>${g.mode!=='wheel'?button('decks','Create / Edit Game Decks'):''}<label class=check><input id=party-playing type=checkbox checked> I’m playing too</label><p class=muted>On: answer keys stay hidden until reveal. Off: you facilitate and do not score. A deck author may already know its answers.</p><label for=party-delivery>How people answer</label><select id=party-delivery><option value=phones>Privately on phones</option><option value=spoken>Aloud, judged by the host</option></select><p class=muted>When the host plays too, spoken answers are judged after reveal.</p><label for=party-duration>Answer time (phone rounds)</label><select id=party-duration>${[30,60,90,120,180].map(n=>`<option value=${n} ${n===60?'selected':''}>${n} seconds</option>`).join('')}</select>${button('start','Start Game','',true)}<p class=muted>Up to 25 cards per session. Clue Board uses deck categories and values; the host selects clues. Survey phone rounds accept one answer per team. Word Wheel uses Latin-letter phrases and has no round timer.</p>`:'<p>Waiting for the host to choose a deck and start.</p>'}${scoreboard?`<h3>Session scores</h3><ul>${scoreboard}</ul>`:''}</section>`;
 if(g.stage==='board')return `<section><h2>Choose a clue</h2><p class=muted>The host selects an unused clue. Everyone answers the same clue; no buzzers or wagering in this version.</p><div class=clue-board>${g.board.map(c=>button('select',`${esc(c.category)} · ${c.points}`,`data-index=${c.index} ${!s.host||c.used?'disabled':''}`)).join('')}</div><ul>${scoreboard}</ul></section>`;
 if(g.mode==='wheel')return `<section><h2>${esc(g.category)}</h2><div class=wheel-puzzle>${esc(g.puzzle)}</div><p>Turn: <strong>${esc(name(g.turnId??''))}</strong> · ${g.spin===null?'Spin, buy a vowel, or solve.':'Spin value: '+g.spin}</p><p class=muted>Consonants earn spin × occurrences; vowels cost 250; solving earns 500. Bankrupt clears the current player’s session points.</p><p>Used letters: ${esc(g.letters.join(' ')||'None')}</p>${g.stage==='scored'?`<h3>Puzzle complete</h3><ul>${scoreboard}</ul>${s.host?button('next',g.index+1<g.count?'Next Puzzle':'Back to Lobby','',true):''}`:g.canControl?`${button('spin','Spin',g.spin!==null?'disabled':'',true)}<label for=party-letter>Letter</label><select id=party-letter>${[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].filter(x=>!g.letters.includes(x)).map(x=>`<option>${x}</option>`).join('')}</select>${button('letter','Guess / Buy Letter')}<label for=party-solution>Solution</label><input id=party-solution maxlength=300 autocomplete=off>${button('solve','Solve Puzzle')}${s.host&&!g.hostPlaying&&g.delivery==='spoken'?`<div class=actions>${button('spoken-solve','Spoken solution: Correct','data-correct=true')}${button('spoken-solve','Incorrect','data-correct=false')}</div>`:''}`:'<p>Waiting for the current player.</p>'}<ul>${g.stage!=='scored'?scoreboard:''}</ul></section>`;
 const keys=g.key?`<section><h3>${g.mode==='survey'?'Answer board':'Accepted answer'}</h3>${g.key.map((a,i)=>`<p>${g.mode==='survey'&&g.delivery==='spoken'&&g.stage==='answering'&&s.host&&!g.hostPlaying?button('board-reveal',g.revealed.includes(i)?`${esc(a.text)} · ${a.points}`:`Reveal ${i+1}: ${esc(a.text)} · ${a.points}`,`data-index=${i} ${g.revealed.includes(i)?'disabled':''}`):`<strong>${esc(a.text)}</strong>${g.mode==='survey'?' · '+a.points+' points':''}`}<small> ${a.aliases.length?'Also: '+esc(a.aliases.join(', ')):''}</small></p>`).join('')}${g.mode==='survey'&&g.delivery==='spoken'&&g.stage==='answering'&&s.host&&!g.hostPlaying?`<p>Strikes: ${g.strikes} / 3</p>${button('strike','Add Strike',g.strikes>=3?'disabled':'')}<p class=muted>Host manages team turns and steals aloud. Set the team’s points below before revealing/scoring.</p>`:''}</section>`:'';
 const entities=g.participants;
 const judge=(rows:{id:string;text:string;points:number;automatic?:number}[])=>rows.map(row=>`<article class=category-review><h3>${esc(name(row.id))}</h3><p>${esc(row.text||'Spoken answer / no submission')}</p><p>${row.points} points${row.automatic!==undefined?' · automatic: '+row.automatic:''}</p>${s.host?`<label for="points-${esc(row.id)}">Award points</label><input id="points-${esc(row.id)}" data-party-points="${esc(row.id)}" type=number min=0 max=10000 value=${row.points}>${button('mark','Save Ruling',`data-player="${esc(row.id)}"`)}${row.automatic!==undefined?button('mark','Use Automatic',`data-player="${esc(row.id)}" data-auto=true`):''}`:''}</article>`).join('');
 return `<section><h2>${esc(g.category)}${g.mode==='survey'?'':' · '+g.points+' points'}</h2><div class=party-question>${esc(g.question)}</div><p class=muted>Question ${g.index+1} of ${g.count}</p>${g.stage==='answering'?`${g.delivery==='phones'?`<strong id=party-clock></strong>${g.canAnswer?`<label for=party-answer>Your ${team?'team’s ':''}answer</label><input id=party-answer maxlength=300 autocomplete=off value="${esc(g.own.text)}"><p id=party-save-state class=muted>Answers are private. Changes save after a brief pause.</p>`:`<p>${s.host&&!g.hostPlaying?'You are facilitating.':'Your team captain submits the answer.'}</p>${team&&g.hostPlaying||team&&!s.host?`<p>Team answer: ${esc(g.own.text||'Not submitted yet')}</p>`:''}`}`:'<p>Answer aloud. The host judges spoken answers.</p>'}${s.host?button('reveal','Reveal & Review','',true):'<p>Waiting for reveal.</p>'}`:''}</section>${keys}${g.mode==='survey'&&g.delivery==='spoken'&&g.stage==='answering'&&!s.host?`<p>Strikes: ${g.strikes} / 3</p>`:''}${g.stage==='answering'&&g.delivery==='spoken'&&s.host&&!g.hostPlaying?judge(entities.map(id=>({id,text:'',points:g.livePoints[id]??0}))):''}${g.review?`<h3>${g.stage==='scored'?'Round scores':'Review answers'}</h3>${g.stage==='review'?'<p class=muted>Exact answers and listed alternatives are accepted automatically. The host can accept synonyms or reject disputed answers.</p>':''}${g.stage==='scored'?g.review.map(r=>`<p>${esc(name(r.id))}: ${r.points} this round · ${g.totals[r.id]??0} total</p>`).join(''):judge(g.review)}${s.host?button(g.stage==='scored'?'next':'finalize',g.stage==='scored'?'Continue':'Finalize Scores','',true):''}`:''}`;
}
