import type {TeamGame,HeadbandsRound} from './games.js';
import type {Round} from './model.js';
import {esc,button} from './ui.js';
import type {TabooGame,TabooRound} from './taboo.js';
export function tabooEnd(match:TabooGame,game:TabooRound):string {
  return `<section class="game round-end taboo-end"><div class="game-status">${esc(match.teams[match.teamIndex]!)} · Round ${match.number}</div><div class="prompt" aria-live="polite">${game.reason==='complete'?'Deck complete!':game.reason==='time'?'Time’s up!':'Round ended'}</div><p class="end-summary">Round score: ${game.score} · ${game.results.filter(r=>r.outcome==='Correct').length} correct · ${game.results.filter(r=>r.outcome==='Taboo').length} violations</p><div class="game-controls end-controls"><div class="taboo-totals">${match.teams.map((name,i)=>`<div><span>${esc(name)}</span><strong>${match.scores[i]} ${match.scores[i]===1?'point':'points'}</strong></div>`).join('')}</div>${button('taboo-next-round',`Next Round: ${esc(match.teams[match.number%match.teams.length]!)}`,'primary full')}<div class="end-secondary">${button('game-setup','Setup','quiet')}${button('finish-game','Finish Game','quiet')}</div></div></section><details class="panel round-extras"><summary>Review round cards</summary><ul>${game.results.map(r=>`<li>${esc(r.card.text)} · ${r.outcome}</li>`).join('')}</ul>${game.reason!=='complete'?`<p>Unanswered: ${esc(game.current.text)}</p>`:''}</details>`;
}
export function catchphraseEnd(match:TeamGame,round:Round):string {
  const title=round.remaining===0?'Time’s up!':'Round ended';
  return `<section class="game round-end"><div class="game-status"><span class="tag">Round ${match.number}</span><span class="tag">${match.scored?'Point settled':'Who gets the point?'}</span></div><div class="prompt" aria-live="polite">${title}</div><p class="end-summary">${round.passed} cards advanced</p><div class="game-controls end-controls"><div class="end-team-grid" style="--team-columns:${Math.min(4,match.teams.length)}" aria-label="Team scores">${match.teams.map((name,i)=>`<button type="button" data-action="award-${i}" class="${match.scored?'settled-team':'primary'}" ${match.scored?'disabled':''}><span>${esc(name)}</span><strong>${match.scores[i]} ${match.scores[i]===1?'point':'points'}</strong>${match.scored?'':'<small>＋1 point</small>'}</button>`).join('')}</div>${match.scored?button('next-team-round','Next Round','primary full'):button('award-none','No point','quiet full')}</div></section><details class="panel round-extras"><summary>Round review & options</summary><p class="muted">${round.remaining===0?'Timer expired':'Ended early'}. Next Card records a move, not a team point.</p><ol>${round.results.map(r=>`<li>${esc(r.text)}</li>`).join('')}</ol><p class="muted">Last card: ${esc(round.current.text)}</p>${button('game-setup','Change Deck or Settings','full quiet')}${button('finish-game','Finish Game','full quiet')}</details>`;
}
export function headsUpEnd(game:HeadbandsRound):string {
  const title=game.reason==='complete'?'Deck complete!':game.reason==='time'?'Time’s up!':'Round ended';
  return `<section class="game round-end"><div class="game-status"><span class="tag">Round complete</span></div><div class="prompt" aria-live="polite">${title}</div><p class="end-summary">${game.score} correct · ${game.passed} passed · ${game.results.filter(r=>r.outcome==='Unanswered').length} unanswered</p><div class="game-controls end-controls">${button('head-replay','Play Again','primary full')}<div class="end-secondary">${button('game-setup','Setup','quiet')}${button('home','Home','quiet')}</div></div></section><details class="panel round-extras"><summary>Review round cards</summary><section class="list-panel results">${game.results.map(r=>`<div class="card-row"><span class="card-text">${esc(r.card.text)}</span><span class="muted">${r.outcome}</span></div>`).join('')}</section></details>`;
}
