import type {MotionSystem} from './motion.js';
export interface TutorialPage {title:string;body:string}
export const welcomePages:TutorialPage[]=[
 {title:'Hey! Thanks for using DeckForge.',body:'<p>The idea is simple:</p><ol><li>Create or import a deck of cards: a list of terms, prompts or questions.</li><li>Use the same deck across games—Heads Up, Catchphrase, Wild Card and more.</li><li>Play with friends, clients, students or colleagues. You decide!</li></ol><p>Play is for social games. Work includes facilitated activities and study. Decks is your shared library.</p>'},
 {title:'Want to get fancy?',body:'<ol><li>Add an optional back for flashcard review or question-and-answer content. Link Trivia uses its own Game Deck editor.</li><li>Create Taboo cards with an answer and five forbidden words.</li><li>Add reusable Activities to a deck. Use <strong>{card}</strong> wherever the card belongs.</li></ol><p>A Feelings card can show “Sad” on its own, or “I last felt <strong>Sad</strong> when…” or “Act out <strong>Sad</strong>.” Activities work in Jenga and Wild Card.</p>'},
 {title:'Bring everyone into the game.',body:'<p>Link offers online multiplayer, including Categories, word puzzles and more. Create a room or join with a room code; players use their own devices.</p><p>Link is a work in progress and needs an internet connection. Your personal deck library stays local unless you explicitly share or export content.</p><p>The one-device modes work offline after the app is cached. Keep a backup of decks you care about.</p>'}
];
export const deckPages:TutorialPage[]=[
 {title:'One library. Many ways to play.',body:'<p>Create a regular deck for words, prompts or questions. Open it to add/edit cards, reorder them or add an optional back.</p><p>Bulk Add accepts pasted lines, TXT files, CSV files and Front/Back text separated by a tab. You can review the import before saving.</p><p>Use <strong>Use this deck</strong> to jump into a compatible mode with the deck already selected.</p>'},
 {title:'Make the deck your own.',body:'<p>Choose an emoji under Deck icon. The pencil beside the settings button renames the deck.</p><p>Cards and Activities have separate editor tabs. Activities belong to the whole deck; use <strong>{card}</strong> to insert the current card.</p><p>Deck organization sets Play/Work/Both recommendations and Available in modes. Show All Decks lets you experiment; Jenga requires exactly 54 cards.</p>'},
 {title:'Organize, share and protect.',body:'<p>Search or filter the library. Swipe left to reveal Delete, then tap to confirm; a swipe alone never deletes a deck.</p><p>Deck options includes duplication, duplicate checking, recent-card memory, resetting recent draws and backup. Keep a saved backup outside the app.</p><p>Taboo Decks and Game Decks have separate editors under More Deck Tools. Game Decks support richer Link questions and survey answers.</p>'}
];
export const modePages:Record<string,TutorialPage[]>={
 prompts:[{title:'Wild Card',body:'<p>Select one or several decks, then draw a prompt. Each selected deck has an equal chance, regardless of size.</p><p>Use it for charades, Pictionary, 20 Questions, conversation starters or your own activity. Draw again when ready. Optional Activities come from the selected card’s deck.</p>'}],
 catchphrase:[{title:'Catchphrase',body:'<p>Choose a deck, teams and timer. After the three-second countdown, describe the word without saying it.</p><p>When guessed, tap Next Card and pass the phone to the next team. At the buzzer, award a point to a team or choose No point, then start the next round.</p><p>For standard play, give spoken descriptions without saying the answer <strong>or any part of it</strong>. No gestures, sound effects, word or letter counts, or hints like “it starts with…” a letter.</p><p>Agree on the rules before starting. Keep clues respectful, choose content that suits your group, and let anyone pass on an uncomfortable prompt.</p><p>The game clock is hidden. Pause stops timing and sound. Leaving the app pauses the round. Random draws favor fresh cards when Recent Card Memory is on, then repeat after the deck is used.</p>'}],
 taboo:[{title:'Taboo',body:'<p>Use a Taboo deck: one answer and five forbidden words per card. Teams take turns giving clues; someone from the other team watches for forbidden words.</p><p>After the three-second countdown, Correct earns 1 point, Pass earns 0 and Taboo subtracts 1. The round ends at the buzzer or when the deck is complete.</p><p>Results update the current team’s total. Next Round hands the turn to the next team.</p>'}],
 headbands:[{title:'Heads Up',body:'<p>Choose a deck and timer. With tilt enabled, rotate to landscape and hold the screen facing your friends at your forehead. Keep steady for the countdown and calibration.</p><p>Friends give clues. Tilt down for Correct and up for Pass, then return to the starting position. Turn off tilt to use buttons instead.</p><p>For standard play, give spoken descriptions without saying the answer <strong>or any part of it</strong>. No gestures, sound effects, word or letter counts, or hints like “it starts with…” a letter.</p><p>Agree on the rules before starting. Keep clues respectful, choose content that suits your group, and let anyone pass on an uncomfortable prompt.</p><p>Each card appears once per round. The round ends when time or cards run out.</p>'}],
 flashcards:[{title:'Flashcards',body:'<p>Choose Front → Back or Back → Front. Tap the card or Flip to reveal the other side.</p><p>Use Previous, Next and Shuffle to review at your own pace. Missing backs show a helpful message; no answers are invented. This mode has no grading or spaced repetition.</p>'}],
 lookup:[{title:'Jenga',body:'<p>Choose a 54-card deck. Enter a block number to show its corresponding card. Previous, Next and Random change the selected card.</p><p>Activities can be None, Fixed, Random or Cycle. Random offers a reroll that keeps the card. Card numbers follow the deck’s saved order.</p>'}]
};
// Optional house rules are guidance only; they do not alter timers, controls or scoring.
export const variationPages:Record<string,TutorialPage[]>={
 catchphrase:[{title:'Catchphrase: mix it up',body:'<p>These are optional house rules. Choose one together before the round; the app’s controls and scoring stay the same.</p><ul><li><strong>Charades:</strong> act out the prompt silently. Gestures are allowed in this variation; no spoken clues.</li><li><strong>One-word clues:</strong> give just one synonym or associated word per card. Never use the answer or part of it.</li><li><strong>Caveman talk:</strong> use only one-syllable clue words. No answer words or parts, gestures, or letter hints.</li><li><strong>Theme night:</strong> use a deck of shared interests or memories.</li></ul><p>Make exceptions clear in advance so everyone plays by the same rules.</p>'}],
 headbands:[{title:'Heads Up: mix it up',body:'<p>Agree on a variation before starting. Tilt and button controls keep working as usual.</p><ul><li><strong>Silent actors:</strong> friends act out the card instead of describing it. Gestures are allowed; no talking.</li><li><strong>One-word clues:</strong> each clue-giver offers one related word, without the answer or any part of it.</li><li><strong>Caveman talk:</strong> describe with one-syllable words only.</li><li><strong>One clue-giver:</strong> take turns explaining instead of everyone talking at once.</li></ul><p>The standard no-gesture rule is intentionally relaxed for Silent actors. Keep prompts comfortable for your group.</p>'}],
 prompts:[{title:'Wild Card: pick your activity',body:'<ul><li><strong>Charades:</strong> draw a prompt and act it out silently.</li><li><strong>Pictionary:</strong> draw on paper while others guess; agree whether letters and numbers are allowed.</li><li><strong>20 Questions:</strong> one person sees the prompt; the others ask up to 20 yes/no questions.</li><li><strong>Conversation starters:</strong> share a memory, opinion or story about the drawn card.</li></ul><p>Add Activities for a reusable instruction around each card. There is no automatic timer or scoring here—your group sets the rules.</p>'}],
 taboo:[{title:'Taboo: change the challenge',body:'<p>Keep the answer and all five forbidden words off limits. Agree on extra restrictions before starting.</p><ul><li><strong>One-word clues:</strong> offer one permitted related word per clue.</li><li><strong>Caveman talk:</strong> use only one-syllable words that are not forbidden.</li><li><strong>Collaborative play:</strong> work together to guess as many cards as possible. Use the round score as a shared target rather than a competition.</li></ul><p>The app still uses its usual Correct (+1), Pass (0), Taboo (−1) scoring and team turns. House rules are not enforced automatically.</p>'}],
 flashcards:[{title:'Flashcards: study your way',body:'<ul><li><strong>Say it first:</strong> answer aloud before flipping, then compare.</li><li><strong>Reverse practice:</strong> start Back → Front to recall a term from its definition.</li><li><strong>Partner review:</strong> one person holds the device and reads prompts to the other.</li><li><strong>Teach it:</strong> after flipping, explain the answer in your own words and give an example.</li></ul><p>Shuffle for a fresh order. This is manual review; the app does not grade or track mastery.</p>'}],
 lookup:[{title:'Jenga: beyond a guessing game',body:'<ul><li><strong>Reflection:</strong> pair each numbered card with a Fixed Activity such as “Tell a story about {card}.”</li><li><strong>Mix it up:</strong> use Random Activities; reroll the instruction while keeping the card.</li><li><strong>Practice together:</strong> Cycle Activities to move through a predictable set of exercises.</li><li><strong>No tower needed:</strong> use numbered slips or choose Previous, Next or Random from the screen.</li></ul><p>A facilitator can keep the phone and read prompts aloud. Always allow a pass; card numbers remain tied to the saved deck order.</p>'}]
};
export function mountTutorial(pages:readonly TutorialPage[],dismiss:()=>Promise<void>,motion:MotionSystem):void {
 if(document.querySelector('dialog[open]'))return;
 const previous=document.activeElement as HTMLElement|null,dialog=document.createElement('dialog');dialog.className='safety-dialog tutorial-dialog';dialog.setAttribute('aria-labelledby','tutorial-title');let index=0,busy=false;
 const close=async()=>{if(busy)return;busy=true;try{await dismiss();motion.closeDialog(dialog,()=>{dialog.close();dialog.remove();if(previous?.isConnected)previous.focus({preventScroll:true});});}catch{busy=false;dialog.querySelector('[role=status]')!.textContent='Could not save this preference. Try again.';}};
 const render=()=>{const page=pages[index]!;dialog.innerHTML=`<span class="safety-icon" aria-hidden="true">▤</span><p class="muted">${index+1} / ${pages.length}</p><h2 id="tutorial-title">${page.title}</h2>${page.body}<p role="status"></p><div class="form-actions">${index?'<button type="button" data-tutorial="back">Back</button>':''}<button type="button" class="primary" data-tutorial="next">${index===pages.length-1?'Got it':'Next'}</button></div>`;dialog.querySelector<HTMLButtonElement>('[data-tutorial=next]')!.focus();};
 dialog.addEventListener('click',event=>{const action=(event.target as HTMLElement).closest<HTMLElement>('[data-tutorial]')?.dataset.tutorial;if(busy)return;if(action==='back'){index--;render();}else if(action==='next'){if(index===pages.length-1)void close();else{index++;render();}}});
 dialog.addEventListener('cancel',event=>{event.preventDefault();void close();});document.body.append(dialog);render();dialog.showModal();motion.openDialog(dialog);
}
