import {roomRequest} from './room-transport.js';
export interface AudienceState {code:string;serverNow:number;round:number;stage:string;question:string;category:string;points:number;index:number;count:number;deadline:number;players:{id:string;name:string}[];answer:string;results:{id:string;text:string;points:number}[];totals:Record<string,number>}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function audienceMarkup(s:AudienceState){const name=(id:string)=>s.players.find(p=>p.id===id)?.name??'Player';return `<div class=tv-heading><span>DeckForge · Trivia</span><strong>Room ${esc(s.code)}</strong></div>${s.stage==='lobby'?`<h1>Join the game</h1><p class=tv-prompt>${esc(s.code)}</p><p>${s.players.length} players · waiting for the host</p>`:`<p class=muted>${esc(s.category)} · ${s.points} points · Question ${s.index+1} of ${s.count}</p><h1 class=tv-prompt>${esc(s.question)}</h1>${s.stage==='answering'?'<p>Answer on your own device</p><strong id=tv-clock></strong>':`<p class=tv-answer>Answer: ${esc(s.answer)}</p><div class=tv-results>${s.results.map(r=>`<div><strong>${esc(name(r.id))}</strong><span>${esc(r.text||'No typed answer')}</span><strong>${r.points} points${s.stage==='scored'?' · '+(s.totals[r.id]??0)+' total':''}</strong></div>`).join('')}</div>`}`}`;}
export function mountAudience(root:HTMLElement,code:string,secret:string):()=>void{
 const life=new AbortController();let polling=false,state:AudienceState|undefined,offset=0,last='',failure='';
 document.body.classList.add('tv-audience');root.innerHTML='<section class=tv-frame><p>Connecting to TV View…</p></section><div class=tv-tools><button type=button id=tv-fullscreen>Full Screen</button><button type=button id=tv-exit>Exit TV View</button><p id=tv-connection role=status></p></div>';
 const frame=root.querySelector<HTMLElement>('.tv-frame')!,status=root.querySelector<HTMLElement>('#tv-connection')!;
 root.querySelector('#tv-exit')!.addEventListener('click',()=>{const url=new URL(location.href);url.searchParams.delete('tv');url.hash='';location.replace(url.href);},{signal:life.signal});
 root.querySelector('#tv-fullscreen')!.addEventListener('click',()=>{if(document.documentElement.requestFullscreen)void document.documentElement.requestFullscreen().catch(()=>status.textContent='Use the device’s full-screen or landscape controls.');else status.textContent='Rotate into landscape, then use your device’s screen-mirroring controls.';},{signal:life.signal});
 function clock(){if(!state)return;const el=root.querySelector('#tv-clock');if(el){const n=Math.max(0,Math.ceil((state.deadline-Date.now()-offset)/1000));el.textContent=state.deadline?(n?`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`:'Waiting for reveal…'):'';}}
 async function poll(){if(polling||life.signal.aborted||document.hidden)return;polling=true;try{const {response,body}=await roomRequest<{audience?:AudienceState;error?:string}>('audience-state',{},code,secret,life.signal);if(life.signal.aborted)return;if(!response.ok){if(response.status===401||response.status===410){state=undefined;frame.innerHTML='<h1>TV link ended</h1><p>Ask the host for a new TV link, or create another room.</p>';clearInterval(timer);}throw new Error(body.error??'TV connection unavailable.');}const next=body.audience!;offset=next.serverNow-Date.now();const content=audienceMarkup(next);state=next;if(content!==last){frame.innerHTML=content;last=content;}failure='';status.textContent='Connected · public audience screen';clock();}catch(e){if(life.signal.aborted)return;failure=String(e);status.textContent=failure+' · internet required';if(state&&state.stage==='answering'){frame.innerHTML='<h1>Connection lost</h1><p>Reconnecting. The host’s game continues.</p>';last='';}}finally{polling=false;}}
 const timer=window.setInterval(()=>void poll(),2000),ticker=window.setInterval(clock,200);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void poll();},{signal:life.signal});window.addEventListener('online',()=>void poll(),{signal:life.signal});void poll();
 return ()=>{life.abort();clearInterval(timer);clearInterval(ticker);document.body.classList.remove('tv-audience');};
}
